#!/bin/bash

apt-get install \
  'autoconf' \
  'automake' \
  'autopoint' \
  'bash' \
  'bison' \
  'bzip2' \
  'cmake' \
  'cowsay' \
  'curl' \
  'espeak' \
  'flex' \
  'flex' \
  'g++' \
  'gettext' \
  'git' \
  'gperf' \
  'intltool' \
  'libasound2-dev' \
  'libboost-all-dev' \
  'libbullet-dev' \
  'libffi-dev' \
  'libgsl0-dev' \
  'libltdl-dev' \
  'libopencv-dev' \
  'libqwt-dev' \
  'libsdl2-dev' \
  'libssl-dev' \
  'libtool' \
  'libxml-parser-perl' \
  'libxtst-dev' \
  'lynx' \
  'lyx' \
  'make' \
  'make' \
  'openjdk-8-jre' \
  'openssl' \
  'p7zip-full'\
  'patch' \
  'perl' \
  'pkg-config' \
  'qt4-demos' \
  'qt4-doc' \
  'qt4-doc-html' \
  'qt5-doc' \
  'qt5-doc-html' \
  'qtbase5-doc-html' \
  'qtbase5-examples' \
  'qtcreator' \
  'r-base' \
  'scons' \
  'sed' \
  'tidy' \
  'tmux' \
  'unzip' \
  'vim' \
  'wget' \
  'witty-dev' \
  'xz-utils'